/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oi_PieChart */

#ifndef _Included_oi_PieChart
#define _Included_oi_PieChart
#ifdef __cplusplus
extern "C" {
#endif
#undef oi_PieChart_FOCUS_TRAVERSABLE_UNKNOWN
#define oi_PieChart_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef oi_PieChart_FOCUS_TRAVERSABLE_DEFAULT
#define oi_PieChart_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef oi_PieChart_FOCUS_TRAVERSABLE_SET
#define oi_PieChart_FOCUS_TRAVERSABLE_SET 2L
#undef oi_PieChart_TOP_ALIGNMENT
#define oi_PieChart_TOP_ALIGNMENT 0.0f
#undef oi_PieChart_CENTER_ALIGNMENT
#define oi_PieChart_CENTER_ALIGNMENT 0.5f
#undef oi_PieChart_BOTTOM_ALIGNMENT
#define oi_PieChart_BOTTOM_ALIGNMENT 1.0f
#undef oi_PieChart_LEFT_ALIGNMENT
#define oi_PieChart_LEFT_ALIGNMENT 0.0f
#undef oi_PieChart_RIGHT_ALIGNMENT
#define oi_PieChart_RIGHT_ALIGNMENT 1.0f
#undef oi_PieChart_serialVersionUID
#define oi_PieChart_serialVersionUID -7644114512714619750i64
#undef oi_PieChart_serialVersionUID
#define oi_PieChart_serialVersionUID 4613797578919906343i64
#undef oi_PieChart_INCLUDE_SELF
#define oi_PieChart_INCLUDE_SELF 1L
#undef oi_PieChart_SEARCH_HEAVYWEIGHTS
#define oi_PieChart_SEARCH_HEAVYWEIGHTS 1L
#undef oi_PieChart_NOT_OBSCURED
#define oi_PieChart_NOT_OBSCURED 0L
#undef oi_PieChart_PARTIALLY_OBSCURED
#define oi_PieChart_PARTIALLY_OBSCURED 1L
#undef oi_PieChart_COMPLETELY_OBSCURED
#define oi_PieChart_COMPLETELY_OBSCURED 2L
#undef oi_PieChart_WHEN_FOCUSED
#define oi_PieChart_WHEN_FOCUSED 0L
#undef oi_PieChart_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define oi_PieChart_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef oi_PieChart_WHEN_IN_FOCUSED_WINDOW
#define oi_PieChart_WHEN_IN_FOCUSED_WINDOW 2L
#undef oi_PieChart_UNDEFINED_CONDITION
#define oi_PieChart_UNDEFINED_CONDITION -1L
#undef oi_PieChart_IS_DOUBLE_BUFFERED
#define oi_PieChart_IS_DOUBLE_BUFFERED 0L
#undef oi_PieChart_ANCESTOR_USING_BUFFER
#define oi_PieChart_ANCESTOR_USING_BUFFER 1L
#undef oi_PieChart_IS_PAINTING_TILE
#define oi_PieChart_IS_PAINTING_TILE 2L
#undef oi_PieChart_IS_OPAQUE
#define oi_PieChart_IS_OPAQUE 3L
#undef oi_PieChart_KEY_EVENTS_ENABLED
#define oi_PieChart_KEY_EVENTS_ENABLED 4L
#undef oi_PieChart_FOCUS_INPUTMAP_CREATED
#define oi_PieChart_FOCUS_INPUTMAP_CREATED 5L
#undef oi_PieChart_ANCESTOR_INPUTMAP_CREATED
#define oi_PieChart_ANCESTOR_INPUTMAP_CREATED 6L
#undef oi_PieChart_WIF_INPUTMAP_CREATED
#define oi_PieChart_WIF_INPUTMAP_CREATED 7L
#undef oi_PieChart_ACTIONMAP_CREATED
#define oi_PieChart_ACTIONMAP_CREATED 8L
#undef oi_PieChart_CREATED_DOUBLE_BUFFER
#define oi_PieChart_CREATED_DOUBLE_BUFFER 9L
#undef oi_PieChart_IS_PRINTING
#define oi_PieChart_IS_PRINTING 11L
#undef oi_PieChart_IS_PRINTING_ALL
#define oi_PieChart_IS_PRINTING_ALL 12L
#undef oi_PieChart_IS_REPAINTING
#define oi_PieChart_IS_REPAINTING 13L
#undef oi_PieChart_WRITE_OBJ_COUNTER_FIRST
#define oi_PieChart_WRITE_OBJ_COUNTER_FIRST 14L
#undef oi_PieChart_RESERVED_1
#define oi_PieChart_RESERVED_1 15L
#undef oi_PieChart_RESERVED_2
#define oi_PieChart_RESERVED_2 16L
#undef oi_PieChart_RESERVED_3
#define oi_PieChart_RESERVED_3 17L
#undef oi_PieChart_RESERVED_4
#define oi_PieChart_RESERVED_4 18L
#undef oi_PieChart_RESERVED_5
#define oi_PieChart_RESERVED_5 19L
#undef oi_PieChart_RESERVED_6
#define oi_PieChart_RESERVED_6 20L
#undef oi_PieChart_WRITE_OBJ_COUNTER_LAST
#define oi_PieChart_WRITE_OBJ_COUNTER_LAST 21L
#undef oi_PieChart_REQUEST_FOCUS_DISABLED
#define oi_PieChart_REQUEST_FOCUS_DISABLED 22L
#undef oi_PieChart_INHERITS_POPUP_MENU
#define oi_PieChart_INHERITS_POPUP_MENU 23L
#undef oi_PieChart_OPAQUE_SET
#define oi_PieChart_OPAQUE_SET 24L
#undef oi_PieChart_AUTOSCROLLS_SET
#define oi_PieChart_AUTOSCROLLS_SET 25L
#undef oi_PieChart_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define oi_PieChart_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef oi_PieChart_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define oi_PieChart_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
#undef oi_PieChart_borders
#define oi_PieChart_borders 20L
#undef oi_PieChart_pieBorder
#define oi_PieChart_pieBorder 50L
/*
 * Class:     oi_PieChart
 * Method:    getData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oi_PieChart_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
