/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oi_XYGraph */

#ifndef _Included_oi_XYGraph
#define _Included_oi_XYGraph
#ifdef __cplusplus
extern "C" {
#endif
#undef oi_XYGraph_FOCUS_TRAVERSABLE_UNKNOWN
#define oi_XYGraph_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef oi_XYGraph_FOCUS_TRAVERSABLE_DEFAULT
#define oi_XYGraph_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef oi_XYGraph_FOCUS_TRAVERSABLE_SET
#define oi_XYGraph_FOCUS_TRAVERSABLE_SET 2L
#undef oi_XYGraph_TOP_ALIGNMENT
#define oi_XYGraph_TOP_ALIGNMENT 0.0f
#undef oi_XYGraph_CENTER_ALIGNMENT
#define oi_XYGraph_CENTER_ALIGNMENT 0.5f
#undef oi_XYGraph_BOTTOM_ALIGNMENT
#define oi_XYGraph_BOTTOM_ALIGNMENT 1.0f
#undef oi_XYGraph_LEFT_ALIGNMENT
#define oi_XYGraph_LEFT_ALIGNMENT 0.0f
#undef oi_XYGraph_RIGHT_ALIGNMENT
#define oi_XYGraph_RIGHT_ALIGNMENT 1.0f
#undef oi_XYGraph_serialVersionUID
#define oi_XYGraph_serialVersionUID -7644114512714619750i64
#undef oi_XYGraph_serialVersionUID
#define oi_XYGraph_serialVersionUID 4613797578919906343i64
#undef oi_XYGraph_INCLUDE_SELF
#define oi_XYGraph_INCLUDE_SELF 1L
#undef oi_XYGraph_SEARCH_HEAVYWEIGHTS
#define oi_XYGraph_SEARCH_HEAVYWEIGHTS 1L
#undef oi_XYGraph_NOT_OBSCURED
#define oi_XYGraph_NOT_OBSCURED 0L
#undef oi_XYGraph_PARTIALLY_OBSCURED
#define oi_XYGraph_PARTIALLY_OBSCURED 1L
#undef oi_XYGraph_COMPLETELY_OBSCURED
#define oi_XYGraph_COMPLETELY_OBSCURED 2L
#undef oi_XYGraph_WHEN_FOCUSED
#define oi_XYGraph_WHEN_FOCUSED 0L
#undef oi_XYGraph_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define oi_XYGraph_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef oi_XYGraph_WHEN_IN_FOCUSED_WINDOW
#define oi_XYGraph_WHEN_IN_FOCUSED_WINDOW 2L
#undef oi_XYGraph_UNDEFINED_CONDITION
#define oi_XYGraph_UNDEFINED_CONDITION -1L
#undef oi_XYGraph_IS_DOUBLE_BUFFERED
#define oi_XYGraph_IS_DOUBLE_BUFFERED 0L
#undef oi_XYGraph_ANCESTOR_USING_BUFFER
#define oi_XYGraph_ANCESTOR_USING_BUFFER 1L
#undef oi_XYGraph_IS_PAINTING_TILE
#define oi_XYGraph_IS_PAINTING_TILE 2L
#undef oi_XYGraph_IS_OPAQUE
#define oi_XYGraph_IS_OPAQUE 3L
#undef oi_XYGraph_KEY_EVENTS_ENABLED
#define oi_XYGraph_KEY_EVENTS_ENABLED 4L
#undef oi_XYGraph_FOCUS_INPUTMAP_CREATED
#define oi_XYGraph_FOCUS_INPUTMAP_CREATED 5L
#undef oi_XYGraph_ANCESTOR_INPUTMAP_CREATED
#define oi_XYGraph_ANCESTOR_INPUTMAP_CREATED 6L
#undef oi_XYGraph_WIF_INPUTMAP_CREATED
#define oi_XYGraph_WIF_INPUTMAP_CREATED 7L
#undef oi_XYGraph_ACTIONMAP_CREATED
#define oi_XYGraph_ACTIONMAP_CREATED 8L
#undef oi_XYGraph_CREATED_DOUBLE_BUFFER
#define oi_XYGraph_CREATED_DOUBLE_BUFFER 9L
#undef oi_XYGraph_IS_PRINTING
#define oi_XYGraph_IS_PRINTING 11L
#undef oi_XYGraph_IS_PRINTING_ALL
#define oi_XYGraph_IS_PRINTING_ALL 12L
#undef oi_XYGraph_IS_REPAINTING
#define oi_XYGraph_IS_REPAINTING 13L
#undef oi_XYGraph_WRITE_OBJ_COUNTER_FIRST
#define oi_XYGraph_WRITE_OBJ_COUNTER_FIRST 14L
#undef oi_XYGraph_RESERVED_1
#define oi_XYGraph_RESERVED_1 15L
#undef oi_XYGraph_RESERVED_2
#define oi_XYGraph_RESERVED_2 16L
#undef oi_XYGraph_RESERVED_3
#define oi_XYGraph_RESERVED_3 17L
#undef oi_XYGraph_RESERVED_4
#define oi_XYGraph_RESERVED_4 18L
#undef oi_XYGraph_RESERVED_5
#define oi_XYGraph_RESERVED_5 19L
#undef oi_XYGraph_RESERVED_6
#define oi_XYGraph_RESERVED_6 20L
#undef oi_XYGraph_WRITE_OBJ_COUNTER_LAST
#define oi_XYGraph_WRITE_OBJ_COUNTER_LAST 21L
#undef oi_XYGraph_REQUEST_FOCUS_DISABLED
#define oi_XYGraph_REQUEST_FOCUS_DISABLED 22L
#undef oi_XYGraph_INHERITS_POPUP_MENU
#define oi_XYGraph_INHERITS_POPUP_MENU 23L
#undef oi_XYGraph_OPAQUE_SET
#define oi_XYGraph_OPAQUE_SET 24L
#undef oi_XYGraph_AUTOSCROLLS_SET
#define oi_XYGraph_AUTOSCROLLS_SET 25L
#undef oi_XYGraph_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define oi_XYGraph_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef oi_XYGraph_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define oi_XYGraph_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
#undef oi_XYGraph_borders
#define oi_XYGraph_borders 20L
/*
 * Class:     oi_XYGraph
 * Method:    getData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oi_XYGraph_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
